using namespace System
enum Icons
{
    Activedirector
    Analytics
    Analyze
    Applet
    Appliances
    Axure
    Badge
    Bin
    Blues
    Businessgoal
    Casestudy
    Cash
    Certification
    Chain
    Cms
    Combochart
    Copilot
    Csharp
    Cybersecurity
    Database
    Databaseadministrator
    Databaserestore
    Databaseserver
    Documentbug
    Done
    Edge
    Electronicbrain
    Exitasign
    Exterior
    Filepath
    Fullversion
    Generalocr
    GitHub
    Goal
    Goalcollaborative
    Hdmicable
    Here
    Highindicatorfilter
    Hitman
    Hologram
    Home
    Intelpowergadget
    Internet
    Keypress
    Laptop
    Laptopalert
    Laptopcheck
    Laptopcoding
    Laptopmedal
    Laptopsend
    Laptopsetting
    LinkedIn
    Logitechoptionsplus
    Lowindicatorfilter
    Luminar
    Microsd
    Microsoftauthenticator
    Name
    Narrator
    Navigation
    Networkgateway
    Networksymbol
    Onscreenkeyboard
    Ordercompleted
    Pcie
    Placeholderthumbnailedifact
    Powerapps
    Powerautomate
    Powerbi
    Powershell
    Powershellise
    Profile
    Project
    Queryinnerjoin
    Queryinnerjoinleft
    Queryinnerjoinright
    Queryouterjoin
    Queryouterjoinleft
    Queryouterjoinright
    Ram
    Region
    Remote
    Remotedesktop
    Sd
    Simulation
    Sound
    Ssh
    Stackoverflow
    Teams
    Toggleoff
    Trial
    Usbtypec
    Useradmin
    Userapply
    Userbusinessman
    Userdecline
    Usergroup
    Userlayoff
    Usertester
    Userunfriend
    Videoidverification
    Visualbasic
    Vsblend
    Website
    Windowsdefender
    Windowsdefragmenter
    Windowsettings
    Windowsmemorydiagnosis
    Windowsupdate
    Workstation
    X64
    X86
    Xmltransformer
}
